### PR TITLE
Updated pyplot and keras calls and updated requirements

### PR DESCRIPTION
**Pull request by peterdekker**
From the matplotlib calls, the seaborn object has been removed, this no
longer works. Keras to_categorical argument changed from nb_classes to
num_classes. Requirements updated with editdistance and h5py.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Hi @pdekker12 ,
The development of Pandora continued in https://github.com/hipster-philology/pandora :)

**Comment by peterdekker** [comment]
@PonteIneptique Thanks, good to know!

**Comment by peterdekker** [comment]
@mikekestemont Could it be mentioned in the Pandora repository that the newest code is in https://github.com/hipster-philology/pandora?

**Comment by mikekestemont** [comment]
I added a short pointer to the README. Apologies for the confusion and many thanks for your commits.

**Pull request closed without merging**
